spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:db-liquibase
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
